### ISSUE TITLE
Windows 11 System.UnauthorizedAccessException: Access to the path <path/to/rom> is denied

### ISSUE THREAD

**Issue by Ndymario** [coop-deluxe/coopdx-patcher#17]
I'm having a strange issue with patching my ROM on a new PC (Windows 11)

```
coopdx-patcher v0.2.3

Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'N:\Games\coopdx-patcher\Super Mario 64 (U) [!].z64' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Patcher.CalculateFileSHA1(String path)
   at Patcher.IsSM64USRom(String path)
   at Patcher.GetROM(String where)
   at Program.Main(String[] args)
```

I am the administrator on my computer.
Running this in an elevated terminal still gives this error as well.

**Comment by Ndymario** [comment]
I fixed the issue. My ROM file was marked as read only for some reason. Making the file not read only via the general tab on the file properties screen fixed this issue.
